version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: wedding-dev
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
volumes:
  data:
